-- DEPRECATED: duplicate of admin-portal approval email.
-- Approval emails are sent once from `supabase/functions/admin-portal` via `send-email`
-- (type: account_approved) with a magic link. Do not re-install this trigger.
--
-- If this trigger was previously applied in your project, run the following in the SQL editor:
--
-- drop trigger if exists trg_profiles_account_approved_email on public.profiles;
-- drop function if exists public.notify_send_account_approved_email();
--
-- Also add column if missing (see main schema.sql):
-- alter table public.profiles add column if not exists approval_email_sent_at timestamptz;
